# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

one_step <- function(n, f, f_base, random_base, c) {
    .Call(`_AcceptReject_one_step`, n, f, f_base, random_base, c)
}

best_y <- function(xlim, f, f_base, continuous, epsilon = 0.001) {
    .Call(`_AcceptReject_best_y`, xlim, f, f_base, continuous, epsilon)
}

